name: Auto Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 写仓库权限
      pages: write     # 新增Pages专用权限
      id-token: read   # OIDC身份验证
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 修正后的标准写法
          publish_dir: ./newyear                     # 源文件目录
          destination_dir: .                         # 部署到根目录
          keep_files: false                          # 清理旧文件
